name: omdb_movies
description: Application that consume OMDB Api

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.18.1
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  redux_epics: ^0.10.0
  built_collection: '>=2.0.0 <4.0.0'
  built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.9.0
  built_value_generator: ^6.0.0

flutter:
  uses-material-design: true